apiVersion: v1
kind: Service
metadata:
  name: content-api
  labels:
    app: content-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: content-api